const { withAppBuildGradle } = require('expo/config-plugins');

/**
 * Signs release builds with a real keystore instead of the SDK's debug key.
 *
 * The template hands every release build to `signingConfigs.debug`, which is the
 * keystore that ships with the Android SDK. Everyone has it, so anyone can sign a
 * modified APK with the same key and Android will accept it as an update to ours.
 * Fine for `adb install`, not fine for anything people download.
 *
 * `android/` is regenerated by prebuild, so editing its build.gradle by hand does
 * not survive. This runs at prebuild time instead.
 *
 * Credentials are read from Gradle properties, which live in
 * ~/.gradle/gradle.properties, outside the repository:
 *
 *   AIM_RELEASE_STORE_FILE      absolute path to the .keystore
 *   AIM_RELEASE_STORE_PASSWORD
 *   AIM_RELEASE_KEY_ALIAS
 *   AIM_RELEASE_KEY_PASSWORD
 *
 * When they are missing the build falls back to the debug key, so a fresh clone
 * still compiles without anyone having to set anything up.
 */

const MARKER = 'AIM_RELEASE_STORE_FILE';

const RELEASE_SIGNING_CONFIG = `
        release {
            if (project.hasProperty('AIM_RELEASE_STORE_FILE')) {
                storeFile file(AIM_RELEASE_STORE_FILE)
                storePassword AIM_RELEASE_STORE_PASSWORD
                keyAlias AIM_RELEASE_KEY_ALIAS
                keyPassword AIM_RELEASE_KEY_PASSWORD
            }
        }`;

const RELEASE_SIGNING_CHOICE = `            // Signed by plugins/withReleaseSigning.js when the AIM_RELEASE_*
            // Gradle properties are present, and by the SDK debug key when they
            // are not, so a clone without a keystore still builds.
            signingConfig project.hasProperty('AIM_RELEASE_STORE_FILE') ? signingConfigs.release : signingConfigs.debug`;

function patch(contents) {
  if (contents.includes(MARKER)) return contents;

  let next = contents;

  // 1. Add a release signing config alongside the template's debug one.
  const configsAnchor = /signingConfigs\s*\{/;
  if (!configsAnchor.test(next)) {
    throw new Error('withReleaseSigning: no signingConfigs block in app/build.gradle');
  }
  next = next.replace(configsAnchor, (m) => `${m}${RELEASE_SIGNING_CONFIG}`);

  // 2. Point the release build type at it. The template line is preceded by its
  //    own warning comment, so take the comment with it.
  const choiceAnchor =
    /[ \t]*\/\/ Caution! In production[^\n]*\n[ \t]*\/\/ see https:\/\/reactnative\.dev[^\n]*\n[ \t]*signingConfig signingConfigs\.debug/;
  if (choiceAnchor.test(next)) {
    next = next.replace(choiceAnchor, RELEASE_SIGNING_CHOICE);
  } else {
    // Template wording changed. Fall back to the release block's own assignment.
    const releaseBlock = /(release\s*\{[^}]*?)signingConfig signingConfigs\.debug/;
    if (!releaseBlock.test(next)) {
      throw new Error('withReleaseSigning: no release signingConfig to replace');
    }
    next = next.replace(releaseBlock, `$1${RELEASE_SIGNING_CHOICE.trimStart()}`);
  }

  return next;
}

/**
 * @type {import('expo/config-plugins').ConfigPlugin}
 */
const withReleaseSigning = (config) =>
  withAppBuildGradle(config, (cfg) => {
    if (cfg.modResults.language !== 'groovy') {
      throw new Error('withReleaseSigning: expected a Groovy build.gradle');
    }
    cfg.modResults.contents = patch(cfg.modResults.contents);
    return cfg;
  });

module.exports = withReleaseSigning;
module.exports.patch = patch;
